import { Feather, FileText } from 'lucide-react';

export default function WelcomeStep({ userData, setUserData, onStart }) {
    const handleInputChange = (e) => {
        const { name, value } = e.target;
        setUserData(prev => ({ ...prev, [name]: value }));
    };
    
    const isStudent = userData.occupation === 'Student' || userData.occupation === 'Researcher';
    const isOtherOccupation = userData.occupation === 'Other';
    const isOtherMajor = userData.major === 'Other';

    const handleSubmit = (e) => {
        e.preventDefault();
        onStart();
    }

    return (
        <div className="min-h-screen w-full flex items-center justify-center bg-gray-50 p-4 font-sans">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 max-w-5xl w-full">
                
                {/* --- Cột Giới thiệu (Bên trái) --- */}
                <div className="flex flex-col justify-center text-center lg:text-left">
                    <Feather size={48} className="text-indigo-500 mx-auto lg:mx-0" />
                    <h1 className="mt-4 text-4xl font-bold text-gray-900 leading-tight">
                        AI Sketch Study: <br />
                        <span className="text-indigo-600">So sánh kết quả sketch</span>
                    </h1>
                    
                    <div className="mt-6 space-y-4">
                        <p className="text-gray-700 leading-relaxed text-justify">
                            Chào bạn, cảm ơn bạn đã tham gia nghiên cứu này!
                            Trong khảo sát này, bạn sẽ so sánh các bản sketch được tạo bởi hai phương pháp AI khác nhau từ cùng một ảnh nội dung đầu vào.
                            Hãy đánh giá mỗi kết quả dựa trên độ đẹp, độ rõ ràng, khả năng giữ nội dung chính và sự mạch lạc của cấu trúc sketch.
                        </p>

                        <p className="text-gray-500 text-sm leading-relaxed text-justify italic border-l-2 border-indigo-100 pl-4">
                            In this study, you will compare sketch outputs generated by two AI methods from the same input content image.
                            Please evaluate each result based on visual quality, readability, content preservation, and structural coherence.
                        </p>
                        </div>
                </div>

                {/* --- Cột Form (Bên phải) --- */}
                <div className="bg-white p-8 rounded-2xl shadow-xl">
                    <div className="flex items-center mb-6">
                        <FileText className="text-gray-400 mr-3" size={24}/>
                        <div>
                            <h2 className="text-xl font-semibold text-gray-800">Thông tin người tham gia</h2>
                            <p className="text-sm text-gray-500">Participant Information</p>
                        </div>
                    </div>

                    <form onSubmit={handleSubmit} className="space-y-4">
                        <div>
                            <label className="block text-sm font-medium text-gray-700">
                                Độ tuổi / Age Range
                            </label>
                            <select
                                name="ageRange"
                                value={userData.ageRange || ""}
                                onChange={handleInputChange}
                                className="mt-1 w-full border p-2 rounded-lg"
                                required
                            >
                                <option value="" disabled>Lựa chọn... / Select...</option>
                                <option value="0-5">0-5</option>
                                <option value="6-10">6-10</option>
                                <option value="11-15">11-15</option>
                                <option value="16-20">16-20</option>
                                <option value="21-25">21-25</option>
                                <option value="26-30">26-30</option>
                                <option value="31-35">31-35</option>
                                <option value="36-40">36-40</option>
                                <option value="41-45">41-45</option>
                                <option value="46-50">46-50</option>
                                <option value="51-55">51-55</option>
                                <option value="56-60">56-60</option>
                                <option value="61-65">61-65</option>
                                <option value="66-70">66-70</option>
                                <option value="71-75">71-75</option>
                                <option value="76-80">76-80</option>
                                <option value="80+">80+</option>
                            </select>
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-gray-700">Giới tính / Gender</label>
                            <select name="gender" value={userData.gender} onChange={handleInputChange} className="mt-1 w-full border p-2 rounded-lg" required>
                                <option value="" disabled>Lựa chọn... / Select...</option>
                                <option value="male">Nam / Male</option>
                                <option value="female">Nữ / Female</option>
                                <option value="other">Khác / Other</option>
                                <option value="prefer_not_to_say">Không muốn nói / Prefer not to say</option>
                            </select>
                        </div>
                        
                        {/* --- Nghề nghiệp / Occupation --- */}
                        <div>
                            <label className="block text-sm font-medium text-gray-700">Nghề nghiệp / Occupation</label>
                            <select name="occupation" value={userData.occupation} onChange={handleInputChange} className="mt-1 w-full border p-2 rounded-lg" required>
                                <option value="" disabled>Lựa chọn... / Select...</option>
                                <option value="Student">Sinh viên / Student</option>
                                <option value="Designer">Nhà thiết kế / Designer</option>
                                <option value="Engineer">Kỹ sư / Engineer</option>
                                <option value="Artist">Nghệ sĩ / Artist</option>
                                <option value="Researcher">Nghiên cứu viên / Researcher</option>
                                <option value="Other">Khác / Other</option>
                            </select>
                        </div>

                        {/* --- Chuyên ngành (Nếu là Student/Researcher) --- */}
                        {isStudent && (
                            <div className="animate-fade-in">
                                <label className="block text-sm font-medium text-gray-700">Chuyên ngành / Major</label>
                                <select name="major" value={userData.major} onChange={handleInputChange} className="mt-1 w-full border p-2 rounded-lg" required>
                                    <option value="" disabled>Lựa chọn... / Select...</option>
                                    <option value="IT">Công nghệ thông tin / IT</option>
                                    <option value="ArtDesign">Nghệ thuật & Thiết kế / Art & Design</option>
                                    <option value="Economics">Kinh tế / Economics</option>
                                    <option value="Medicine">Y khoa / Medicine</option>
                                    <option value="Other">Khác / Other</option>
                                </select>
                            </div>
                        )}
                        {isStudent && isOtherMajor && (
                            <div className="animate-fade-in">
                                <label className="block text-sm font-medium text-gray-700">Chuyên ngành của bạn / Your Major</label>
                                <input type="text" name="majorOther" value={userData.majorOther} onChange={handleInputChange} className="mt-1 w-full border p-2 rounded-lg" placeholder="Ví dụ: Ngôn ngữ Anh..." required />
                            </div>
                        )}
                        {isOtherOccupation && (
                            <div className="animate-fade-in">
                                <label className="block text-sm font-medium text-gray-700">Nghề nghiệp của bạn / Your Occupation</label>
                                <input type="text" name="occupationOther" value={userData.occupationOther} onChange={handleInputChange} className="mt-1 w-full border p-2 rounded-lg" placeholder="Ví dụ: Bác sĩ, Giáo viên..." required />
                            </div>
                        )}

                        {/* --- Câu hỏi trải nghiệm / Pareidolia Question --- */}
                        <div className="animate-fade-in mt-4 border-t border-gray-200 pt-4">
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                                Bạn có kinh nghiệm về vẽ, thiết kế, minh họa, hoặc đánh giá hình ảnh/sketch không?
                            </label>

                            <p className="text-xs text-gray-400 mb-2">
                                Do you have experience with drawing, design, illustration, or visual/sketch evaluation?
                            </p>

                            <select
                                name="visualExperience"
                                value={userData.visualExperience || ""}
                                onChange={handleInputChange}
                                className="w-full border p-2 rounded-lg"
                                required
                            >
                                <option value="" disabled>Lựa chọn... / Select...</option>
                                <option value="none">Không có kinh nghiệm / No experience</option>
                                <option value="basic">Cơ bản / Basic experience</option>
                                <option value="intermediate">Trung bình / Intermediate experience</option>
                                <option value="advanced">Nhiều kinh nghiệm / Advanced experience</option>
                            </select>
                        </div>

                        <button type="submit" className="mt-6 w-full bg-indigo-600 text-white py-3 rounded-lg hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-all text-base font-semibold transform hover:scale-[1.02]">
                            Bắt đầu đánh giá / Start Evaluation
                        </button>
                    </form>
                </div>
            </div>
        </div>
    );
}